name: note_taker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  provider: ^6.1.1
  record: ^6.1.2
  uuid: ^4.3.3
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  flutter_quill: ^9.6.0
  flutter_quill_extensions: ^9.6.0
  flutter_colorpicker: ^1.0.0
  audioplayers: ^5.2.1
  image_picker: ^1.0.7
  audio_waveforms: ^1.0.5
  fluttertoast: ^8.2.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/notification/

dependency_overrides:
  intl: ^0.19.0
